/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/white_silver_green_residence.glb -t 
Author: Francesco Coldesina (https://sketchfab.com/topfrank2013)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-silver-green-residence-ec516ba32f03403f97954472c5d4b2cf
Title: White Silver Green Residence
*/

import React from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

interface GLTFAction extends THREE.AnimationAction {
  action: THREE.AnimationAction;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
  }
  materials: {
    Base_Stone: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    LR_Water_Tank: THREE.MeshStandardMaterial
    Render_Material_255_255_255: THREE.MeshStandardMaterial
    Roof1: THREE.MeshStandardMaterial
    Site_Foundation001: THREE.MeshStandardMaterial
    Solar_System: THREE.MeshStandardMaterial
    Stoffa: THREE.MeshStandardMaterial
    Structure001: THREE.MeshStandardMaterial
    Tubo: THREE.MeshStandardMaterial
    VetriLamp: THREE.MeshStandardMaterial
    Whitello: THREE.MeshStandardMaterial
    Wood_A: THREE.MeshStandardMaterial
    wire_000000000: THREE.MeshStandardMaterial
    Material__592: THREE.MeshStandardMaterial
    Rubber: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function HouseModel(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/public/models/white_silver_green_residence.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-1272.332, -469.014, -140.7]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.Base_Stone} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.LR_Water_Tank} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Render_Material_255_255_255} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Roof1} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Site_Foundation001} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.Solar_System} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Stoffa} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Structure001} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Tubo} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.VetriLamp} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.Whitello} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Wood_A} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.wire_000000000} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.Material__592} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.Rubber} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/public/models/white_silver_green_residence.glb')
